name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: "${{ secrets.CLOUDTYPE_TOKEN }}"
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: "${{ secrets.CLOUDTYPE_TOKEN }}"
          project: poeroff/nestjs
          stage: main
          yaml: |
            name: himesama-dacko
            app: node@16
            options:
              env:
                - name: DB_HOST
                  value: youtube.cygahsyhplsd.ap-northeast-2.rds.amazonaws.com
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: admin
                - name: DB_PASSWORD
                  value: wqdsdsf123
                - name: DB_NAME
                  value: youtube
                - name: DB_SYNC
                  value: "true"
                - name: CHAR_SET
                  value: utf8mb4
                - name: JWT_SECRET_KEY
                  value: wqdsdsf123
              ports: "4000"
              install: npm ci
              build: npm run build
              start: npm run start:dev
            context:
              git:
                url: git@github.com:kim-sunah/himesama-dacko.git
                ref: main
