name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: poeroff/nestjs
          stage: main
          yaml: |
            name: himesama-dacko
            app: node@20
            options:
              env:
                - name: DB_HOST
                  value: pet.czyokzgn9ldt.ap-northeast-2.rds.amazonaws.com
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: root
                - name: DB_PASSWORD
                  value: timeless02
                - name: DB_NAME
                  value: youtube
                - name: DB_SYNC
                  value: "true"
                - name: CHAR_SET
                  value: utf8mb4
                - name: JWT_SECRET_KEY
                  value: wqdsdsf123
                - name: Youtbe_Api_KEY
                  value: AIzaSyCG-Av5i12FnfYP9x2tPfM68QkdoQppOxI
              ports: "4000"
              install: npm ci
              build: npm run build
              start: npm run start:dev
            context:
              git:
                url: git@github.com:kim-sunah/himesama-dacko.git
                path: backend
                ref: main
